#pragma once

#include "../Range/Aggregate.h"
#include "../Range/All.h"
#include "../Range/Any.h"
#include "../Range/Between.h"
#include "../Range/Collect.h"
#include "../Range/Count.h"
#include "../Range/Drop.h"
#include "../Range/Each.h"
#include "../Range/Filter.h"
#include "../Range/Map.h"
#include "../Range/PartialFoldl.h"
#include "../Range/Reduce.h"
#include "../Range/Reverse.h"
#include "../Range/Seq.h"
#include "../Range/Take.h"
#include "../Range/Transform.h"
